# Generated by Django 4.2.13 on 2024-06-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(blank=True, max_length=29, null=True)),
                ('inadiplente', models.CharField(blank=True, max_length=70, null=True)),
                ('data_carregamento', models.DateField(auto_now=True)),
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
